/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface GraphSchema {
  attributes: {
    [k: string]: unknown;
  };
  options: {
    /**
     * One of mixed, directed or undirected
     */
    type: "mixed" | "directed" | "undirected";
    allowSelfLoops?: boolean;
    multi?: boolean;
  };
  nodes: GraphNodeSchema[];
  edges: GraphEdgeSchema[];
}
export interface GraphNodeSchema {
  key: string;
  attributes: {
    type?: string;
    [k: string]: unknown;
  };
}
export interface GraphEdgeSchema {
  key: string;
  source: string;
  target: string;
  attributes: {
    type?: string;
    [k: string]: unknown;
  };
}
