/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface PatternGraphSchema {
  options: {
    /**
     * One of directed or undirected
     */
    type: "directed" | "undirected";
    allowSelfLoops?: boolean;
    multi?: boolean;
  };
  nodes: PatternNodeSchema[];
  edges: GraphEdgeSchema[];
  nacs?: {
    nodes: PatternNodeSchema[];
    edges: GraphEdgeSchema[];
  };
}
export interface PatternNodeSchema {
  key: string;
  attributes?: {
    [k: string]: number | string | boolean | null | (number | string | boolean)[];
  };
}
export interface GraphEdgeSchema {
  /**
   * The edge's ID
   */
  key: string;
  /**
   * The key of the node at the edge's source
   */
  source: string;
  /**
   * The key of the node at the edge's target
   */
  target: string;
  /**
   * The edges attributes & values
   */
  attributes: {
    type?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(?!type$).*".
     */
    [k: string]: number | string | boolean;
  };
  additionalProperties?: never;
}
