/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

import { GraphNodeSchema } from "./node.schema";

export interface PatterngraphSchema {
  options: {
    /**
     * One of directed or undirected
     */
    type: "directed" | "undirected";
    allowSelfLoops?: boolean;
    multi?: boolean;
  };
  nodes: PatternNodeSchema[];
  edges: GraphEdgeSchema[];
  nacs?: {
    nodes?: PatternNodeSchema[];
    edges?: GraphEdgeSchema[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
export interface PatternNodeSchema extends GraphNodeSchema {
  /**
   * The node's ID, also used as node in an edges source/target etc.
   */
  key: string;
  /**
   * The node's attributes.
   */
  attributes: {
    type?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(?!type$).*".
     */
    [k: string]: number | string | boolean | (number | string | boolean)[];
  };
}
export interface GraphEdgeSchema {
  /**
   * The edge's ID
   */
  key: string;
  /**
   * The key of the node at the edge's source
   */
  source: string;
  /**
   * The key of the node at the edge's target
   */
  target: string;
  /**
   * The edges attributes & values
   */
  attributes: {
    type?: string;
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "^(?!type$).*".
     */
    [k: string]: number | string | boolean | GraphInstantiatedAttributeSchema;
  };
}
export interface GraphInstantiatedAttributeSchema {
  type: string;
  args: {
    [k: string]: unknown;
  };
}
