
// Should update node B with additional attributes
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/update_node_attr_modify.json

// Should delete all attributes from B
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/update_node_attr_delete.json

// Should replace attributes from B
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/update_node_attr_replace.json
