

// ADD EDGES
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/add_edge.json

// UPDATE NODES
// Should update node B with additional attributes
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/update_node_attr_modify.json

// Should delete all attributes from B
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/update_node_attr_delete.json

// Should replace attributes from B
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/update_node_attr_replace.json

// OPTIONS
// Homomorphic matching
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/homomorphic_matching.json

// Isomorphic matching
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/development/isomorphic_matching.json
