POST http://localhost:8080/edge
Content-Type: application/json

{
  "key": "testedge",
  "source": "testnodeA",
  "target": "testnodeB",
  "attributes": {
    "type": "TestType",
    "description": "This is an example relationshio",
    "label": "Relationship label"
  }
}
GET http://localhost:8080/edge/testedge

DELETE http://localhost:8080/edge/testedge