POST http://localhost:8080/grs
Content-Type: application/json

< ../data/grs/hostgraph_only.json


POST http://localhost:8080/grs
Content-Type: application/json

< ../data/grs/hostgraph_w_rules.json


POST http://localhost:8080/grs
Content-Type: application/json

< ../data/grs/hostgraph_w_rules_w_external_replacementgraph.json


// Testcase for a rewrite rule with attribute values instanitated by
// - regexr (regex: (Hello|Howdy|Hi|Bonjour) (World|People|Computers))
// - faker (alphanumeric)
// - jsonLogic (combines different json logic rules, some refer to searchmatch content through jsonPath)
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/grs/hostgraph_w_rules_w_instantiated_attributes.json