# POST http://localhost:8080/hostgraph
# Content-Type: application/json

# < ../data/simple_graph.json

POST http://localhost:8080/grs
Content-Type: application/json

< ../data/hostgraph_only.json


POST http://localhost:8080/grs
Content-Type: application/json

< ../data/hostgraph_w_rules.json


// Testcase for a rewrite rule with attribute values instanitated by regexr (regex: [A-Z][a-z]{2,20})
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/hostgraph_w_rules_w_regex_instantiated_attributes.json