POST http://localhost:8080/node
Content-Type: application/json

{
  "key": "testnode",
  "attributes": {
    "label": "This is the label",
    "description": "This is an example node",
    "type": "TestType"
  }
}

GET http://localhost:8080/node/testnode

GET http://localhost:8080/nodes

DELETE http://localhost:8080/node/testnode

DELETE http://localhost:8080/nodes
