// Import Hostgraph only: Example "UML to Petrinet"
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/usecases/uml_to_petrinet_hostgraph.json

// Import Hostgraph only: Example "UML to Petrinet"
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/grs/uml_to_petrinet.json







// Sierpinski Triangles Example
POST http://localhost:8080/grs
Content-Type: application/json

< ../data/usecases/sierpinsky_triangles.json