# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Check Codebase

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

defaults:
  run:
    working-directory: .

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
    steps:
      - uses: actions/checkout@v4
      - name: Run eslint/tslint
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: install
        run: npm ci

      - name: Run prettier
        run: npm run prettier

      - name: Run eslint/tslint
        run: npm run lint
  test:
    name: Run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - uses: actions/checkout@v4
      - name: Run Vitest Unittests via Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm run test

#      - name: Test Summary
#        uses: test-summary/action@v2
#        with:
#          paths: 'test/results/junit-report.xml'
#        if: always()

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test/results/junit-report.xml
